# 配置MySQL数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webwzb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
  #http配置
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
server:
  port: 8099
---
# jpa相关配置
spring:
  jpa:
    # 更新数据表结构   create:程序运行时创建数据库表(如果有表，先删除再创建)
    #                update：创建表（如果有表,不创建表）
    hibernate:
      ddl-auto: update

    # 在日志中打印出执行sql语句的信息
    show-sql: true


